# Generated by Django 4.1.13 on 2024-03-27 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('module1', '0002_feed'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Neeraj',
            new_name='Amar',
        ),
        migrations.AlterModelTable(
            name='amar',
            table='Amar',
        ),
    ]
